language: php
php:
 - '7.1.9'

services:
 - mysql

before_install:
 - mysql -e 'DROP DATABASE IF EXISTS froxynetwork_test;'
 - mysql -e 'CREATE DATABASE froxynetwork_test;'
 - mysql -u root --default-character-set=utf8 froxynetwork_test < Tests/travis.sql

before_script:
 - composer install --prefer-source --no-interaction

script:
 - vendor/bin/phpunit
 - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
 - bash <(curl -s https://codecov.io/bash)