language: php
php:
 - '7.1.9'

services:
 - mongodb

before_install:
 - sudo pecl install mongodb
 - phpenv config-add travis.ini

before_script:
 - composer install --prefer-source --no-interaction

script:
 - vendor/bin/phpunit
 - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
 - bash <(curl -s https://codecov.io/bash)